/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Util.Calendario;

/**
 *
 * @author rafa_
 */
public class TelaConsultaAlterar extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultaAlterar
     */
    public TelaConsultaAlterar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPrincipalAlterar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        pnConsultaAlterarCalendario = new javax.swing.JPanel();
        tfConsultaAlterarCalendario = new javax.swing.JTextField();
        btConsultaAlterarCalendario = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnPrincipalAlterar.setLayout(null);

        jLabel1.setText("ID: 765002");
        pnPrincipalAlterar.add(jLabel1);
        jLabel1.setBounds(170, 0, 70, 19);

        jLabel2.setText("ICCID:");
        pnPrincipalAlterar.add(jLabel2);
        jLabel2.setBounds(250, 0, 30, 19);

        jTextField1.setText("jTextField1");
        pnPrincipalAlterar.add(jTextField1);
        jTextField1.setBounds(280, 0, 108, 19);

        jLabel3.setText("Cliente:");
        pnPrincipalAlterar.add(jLabel3);
        jLabel3.setBounds(20, 50, 35, 15);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnPrincipalAlterar.add(jComboBox1);
        jComboBox1.setBounds(60, 50, 90, 24);

        jLabel4.setText("Operadora:");
        pnPrincipalAlterar.add(jLabel4);
        jLabel4.setBounds(0, 100, 60, 15);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnPrincipalAlterar.add(jComboBox2);
        jComboBox2.setBounds(60, 100, 90, 24);

        jLabel5.setText("Tipo:");
        pnPrincipalAlterar.add(jLabel5);
        jLabel5.setBounds(20, 140, 23, 15);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnPrincipalAlterar.add(jComboBox3);
        jComboBox3.setBounds(60, 140, 90, 24);

        jLabel6.setText("Status:");
        pnPrincipalAlterar.add(jLabel6);
        jLabel6.setBounds(20, 0, 34, 15);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnPrincipalAlterar.add(jComboBox4);
        jComboBox4.setBounds(60, 0, 56, 24);

        pnConsultaAlterarCalendario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfConsultaAlterarCalendario.setEditable(false);
        pnConsultaAlterarCalendario.add(tfConsultaAlterarCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, -1));

        btConsultaAlterarCalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_calendar_20px.png"))); // NOI18N
        btConsultaAlterarCalendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btConsultaAlterarCalendarioMouseClicked(evt);
            }
        });
        btConsultaAlterarCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultaAlterarCalendarioActionPerformed(evt);
            }
        });
        pnConsultaAlterarCalendario.add(btConsultaAlterarCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 30, 30));

        pnPrincipalAlterar.add(pnConsultaAlterarCalendario);
        pnConsultaAlterarCalendario.setBounds(250, 50, 140, 30);

        jLabel7.setText("Data De Ativação");
        pnPrincipalAlterar.add(jLabel7);
        jLabel7.setBounds(160, 50, 90, 15);

        jButton1.setText("Salvar");
        pnPrincipalAlterar.add(jButton1);
        jButton1.setBounds(310, 140, 73, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(pnPrincipalAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(pnPrincipalAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConsultaAlterarCalendarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConsultaAlterarCalendarioMouseClicked
        Calendario c = new Calendario(tfConsultaAlterarCalendario);
        c.setVisible(true);
        c.setLocation(pnConsultaAlterarCalendario.getX() + 380, pnConsultaAlterarCalendario.getY() - 60);
    }//GEN-LAST:event_btConsultaAlterarCalendarioMouseClicked

    private void btConsultaAlterarCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultaAlterarCalendarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btConsultaAlterarCalendarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultaAlterar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultaAlterarCalendario;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pnConsultaAlterarCalendario;
    private javax.swing.JPanel pnPrincipalAlterar;
    private javax.swing.JTextField tfConsultaAlterarCalendario;
    // End of variables declaration//GEN-END:variables
}
