/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.SinistroDAO;
import Model.Agente;
import Model.GerarPDF;
import Model.Sinistro;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;

/**
 *
 * @author rafa_
 */
public class TelaUparImagens extends javax.swing.JFrame {
    Sinistro sinistro ;
    int iterador;
    List<Agente> agente;
    
    public TelaUparImagens(List<Agente> agente,Sinistro sinistro,int iterador) {
        initComponents();
        this.sinistro = sinistro;
        this.iterador = iterador;
        this.agente = agente;
        lbTitulo.setText("Adicionar as fotos da Equipe: "+agente.get(iterador).getNome());
     
    }

    private TelaUparImagens() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPrincipal = new javax.swing.JPanel();
        btArquivo = new javax.swing.JButton();
        pnImagens = new javax.swing.JPanel();
        btGerarPdf = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btArquivo.setText("Selecione um arquivo");
        btArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btArquivoActionPerformed(evt);
            }
        });
        pnPrincipal.add(btArquivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        javax.swing.GroupLayout pnImagensLayout = new javax.swing.GroupLayout(pnImagens);
        pnImagens.setLayout(pnImagensLayout);
        pnImagensLayout.setHorizontalGroup(
            pnImagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );
        pnImagensLayout.setVerticalGroup(
            pnImagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        pnPrincipal.add(pnImagens, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 65, -1, 430));

        btGerarPdf.setText("GerarPDF");
        btGerarPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarPdfActionPerformed(evt);
            }
        });
        pnPrincipal.add(btGerarPdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 501, -1, -1));

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnPrincipal.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btArquivoActionPerformed
        pnImagens.removeAll();
        repaint();
        JFileChooser arquivo = new JFileChooser();
        arquivo.setDialogTitle("Selecione os arquivos");
        arquivo.setMultiSelectionEnabled(true);
        arquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        
        
        Vector<File> file = new Vector<File>();
        
        int opc = arquivo.showOpenDialog(this);
              ArrayList<JLabel> label = new ArrayList<JLabel>();
              List<Image> imagens = new ArrayList<Image>();
              
              int i =0,j=1;
           //   int x=lbImagem.getX(),y=lbImagem.getY();
              int x=1,y=1;
        if(opc == JFileChooser.APPROVE_OPTION){
            for (File files: arquivo.getSelectedFiles()){
                
              label.add(new JLabel());
              label.get(i).setSize(120, 92);
              if (i==0){
                  label.get(i).setLocation(1,1);
                
             //   x = x+125;
              }else{
                x+= 125;
                if (x > pnImagens.getWidth()){
                    x=1;
                y+=99;  
              label.get(i).setLocation(x,y);
                    
                }else{
                    label.get(i).setLocation(x,y);
                }
              j++;
              }
                try {
                    imagens.add(Image.getInstance(files.getPath()));
                   
            agente.get(iterador).setImagens(imagens);
                } catch (BadElementException ex) {
                    Logger.getLogger(TelaUparImagens.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(TelaUparImagens.class.getName()).log(Level.SEVERE, null, ex);
                }
              ImageIcon img = new ImageIcon(files.getPath());
              label.get(i).setIcon(new ImageIcon(img.getImage().getScaledInstance(120, 92, java.awt.Image.SCALE_DEFAULT )));
           
                pnImagens.add(label.get(i));
                i++;
              
            }
            
            repaint();
//            ImageIcon imagem = new ImageIcon(file.get(0).getPath());
//            ImageIcon imagem2 = new ImageIcon(file.get(1).getPath());
//            lbImagem.setIcon(new ImageIcon(imagem.getImage().getScaledInstance(lbImagem.getWidth(), lbImagem.getHeight(), Image.SCALE_DEFAULT)));
//            
        }
    }//GEN-LAST:event_btArquivoActionPerformed

    private void btGerarPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarPdfActionPerformed
        
    //    missao.get(0).getAgente().setImagens(missao.get(0).getAgente().getImagens());
     
        
        if (iterador+1 == agente.size()){
        GerarPDF pdf = new GerarPDF(sinistro, agente);
            setVisible(false);
        }else{
            
            TelaUparImagens tela = new TelaUparImagens(agente, sinistro, iterador+1);
            tela.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_btGerarPdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUparImagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUparImagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUparImagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUparImagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new TelaUparImagens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btArquivo;
    private javax.swing.JButton btGerarPdf;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel pnImagens;
    private javax.swing.JPanel pnPrincipal;
    // End of variables declaration//GEN-END:variables
}
