package View;

import Model.Isca;
import Util.Calendario;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class TelaAtivacaoIsca extends javax.swing.JFrame {

    ArrayList<Isca> lista = new ArrayList<Isca>();

    public TelaAtivacaoIsca() {
        initComponents();
        taNumeroIsca.setFocusable(true);
        //   tfData.setFormatterFactory(Util.Mascara.getData());

    }

    public ArrayList<Isca> getLista() {
        return lista;
    }

    public void pegarValores() {
        int x = taNumeroIsca.getLineCount();
        ArrayList<Isca> aaa = new ArrayList<Isca>();
        String str1 = tfCalendario.getText();
        int resp;
        /*  for (int i=0;i<str1.length();i++){
            if(str1.charAt(i) == '/'){
                
            }else{
               resp = str1.charAt(i);
            }
        }*/

        Isca consulta = new Isca();
        ArrayList<Integer> naoCadastrados = new ArrayList<Integer>();
        if (cbCliente.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Preencha Todos os campos");
        } else {
            try {

                //  String data = tfData.getText();
                String cliente = String.valueOf(cbCliente.getSelectedItem());

                String str[] = taNumeroIsca.getText().split("\n");

                for (int h = 0; h <= taNumeroIsca.getLineCount() - 1; h++) {
                    if (consulta.PesquisarIsca(Integer.valueOf(str[h]))) {

                        Isca bbb = new Isca();

                        bbb.setID(Integer.valueOf(str[h]));
                        // bbb.setData(data);
                        bbb.setCliente(cliente);
//                        bbb.setData(tfCalendario.getText());
                        bbb.setStatus(true);
                        aaa.add(bbb);

                    } else {
                        naoCadastrados.add(Integer.valueOf(str[h]));
                    }

                }
                   if (!naoCadastrados.isEmpty()){
                       JOptionPane.showMessageDialog(null,"as seguintes isca nao possuem cadastros"+naoCadastrados.toString());
                   }
                //  if (aaa.size() !=  0 ){
                Isca isca = new Isca(aaa);
                limpar();
                /*   }else{
                    lbMsg.setText("essas isca ja possuem cadastro"+aaa.toString());
                lbMsg.setBackground(Color.red);
                lbMsg.setForeground(Color.white);
                System.out.println("essas isca ja possuem cadastro"+aaa.toString());
                }*/
                JOptionPane.showMessageDialog(null,"Ativado com sucesso");
                naoCadastrados = null;

            } catch (NumberFormatException e) {
                System.out.println(e.getStackTrace() + "        " + e.getMessage());
                JOptionPane.showMessageDialog(null, "Campos numero isca contem letra");

            }

        }
    }

    public void limpar() {
        taNumeroIsca.setText("");

        cbCliente.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPrincipalAtivacao = new javax.swing.JPanel();
        lbNomeIsca = new javax.swing.JLabel();
        lbData = new javax.swing.JLabel();
        btAplicar = new javax.swing.JButton();
        lbCliente = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        taNumeroIsca = new javax.swing.JTextArea();
        lbMsg = new javax.swing.JLabel();
        pnCalendario = new javax.swing.JPanel();
        tfCalendario = new javax.swing.JTextField();
        btCalendario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnPrincipalAtivacao.setBackground(new java.awt.Color(255, 255, 255));
        pnPrincipalAtivacao.setForeground(new java.awt.Color(51, 51, 0));
        pnPrincipalAtivacao.setPreferredSize(new java.awt.Dimension(500, 500));

        lbNomeIsca.setBackground(new java.awt.Color(255, 255, 0));
        lbNomeIsca.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbNomeIsca.setForeground(new java.awt.Color(0, 0, 0));
        lbNomeIsca.setText("Numero da isca ");

        lbData.setBackground(new java.awt.Color(255, 255, 255));
        lbData.setForeground(new java.awt.Color(0, 0, 0));
        lbData.setText("Data");

        btAplicar.setText("Aplicar");
        btAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAplicarActionPerformed(evt);
            }
        });

        lbCliente.setForeground(new java.awt.Color(0, 0, 0));
        lbCliente.setText("Cliente");

        cbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Cliente1", "Cliente2", "Cliente3" }));
        cbCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        taNumeroIsca.setBackground(new java.awt.Color(228, 215, 241));
        taNumeroIsca.setColumns(20);
        taNumeroIsca.setRows(5);
        taNumeroIsca.setBorder(null);
        jScrollPane2.setViewportView(taNumeroIsca);

        pnCalendario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfCalendario.setEditable(false);
        pnCalendario.add(tfCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, -1));

        btCalendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_calendar_20px.png"))); // NOI18N
        btCalendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCalendarioMouseClicked(evt);
            }
        });
        btCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalendarioActionPerformed(evt);
            }
        });
        pnCalendario.add(btCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 30, 30));

        javax.swing.GroupLayout pnPrincipalAtivacaoLayout = new javax.swing.GroupLayout(pnPrincipalAtivacao);
        pnPrincipalAtivacao.setLayout(pnPrincipalAtivacaoLayout);
        pnPrincipalAtivacaoLayout.setHorizontalGroup(
            pnPrincipalAtivacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalAtivacaoLayout.createSequentialGroup()
                .addGroup(pnPrincipalAtivacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPrincipalAtivacaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnPrincipalAtivacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnPrincipalAtivacaoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbNomeIsca))
                            .addGroup(pnPrincipalAtivacaoLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnPrincipalAtivacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnPrincipalAtivacaoLayout.createSequentialGroup()
                                        .addGap(106, 106, 106)
                                        .addComponent(lbData))
                                    .addGroup(pnPrincipalAtivacaoLayout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnPrincipalAtivacaoLayout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addComponent(lbCliente))
                                    .addGroup(pnPrincipalAtivacaoLayout.createSequentialGroup()
                                        .addGap(85, 85, 85)
                                        .addComponent(btAplicar))
                                    .addGroup(pnPrincipalAtivacaoLayout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(pnCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(pnPrincipalAtivacaoLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(lbMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnPrincipalAtivacaoLayout.setVerticalGroup(
            pnPrincipalAtivacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalAtivacaoLayout.createSequentialGroup()
                .addComponent(lbMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(pnPrincipalAtivacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnPrincipalAtivacaoLayout.createSequentialGroup()
                        .addComponent(lbNomeIsca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnPrincipalAtivacaoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lbData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAplicar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipalAtivacao, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipalAtivacao, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAplicarActionPerformed

        pegarValores();


    }//GEN-LAST:event_btAplicarActionPerformed

    private void btCalendarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCalendarioMouseClicked
        Calendario c = new Calendario(tfCalendario);
        c.setVisible(true);
        c.setLocation(pnCalendario.getX() + 380, pnCalendario.getY() - 60);


    }//GEN-LAST:event_btCalendarioMouseClicked

    private void btCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalendarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCalendarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtivacaoIsca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtivacaoIsca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtivacaoIsca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtivacaoIsca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtivacaoIsca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAplicar;
    private javax.swing.JButton btCalendario;
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbMsg;
    private javax.swing.JLabel lbNomeIsca;
    private javax.swing.JPanel pnCalendario;
    public javax.swing.JPanel pnPrincipalAtivacao;
    private javax.swing.JTextArea taNumeroIsca;
    private javax.swing.JTextField tfCalendario;
    // End of variables declaration//GEN-END:variables
}
