/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Agente;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author rafa_
 */
public class TelaSinsitroTeste extends javax.swing.JFrame {

    /**
     * Creates new form TelaSinsitroTeste
     */
    public TelaSinsitroTeste() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCadastroSinistro = new javax.swing.JPanel();
        pnPrincipal1 = new javax.swing.JPanel();
        pnOcorrencia = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbClienteSinistro = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbTipoOcorrencia = new javax.swing.JComboBox<>();
        pnVeiculo = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        tfPlaca = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfCarreta = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfModelo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfCor = new javax.swing.JTextField();
        tfValorCarga = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tfCidade = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tfCoordenadas = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfInformante = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tfHoraOcorrencia = new javax.swing.JTextField();
        tfContato = new javax.swing.JTextField();
        btSalvarSinistro = new javax.swing.JButton();
        btLimparSinistro = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        taDescricao = new javax.swing.JTextArea();
        pnCondutor = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tfCPF = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tfContatoCondutor = new javax.swing.JTextField();
        pnAcionamento = new javax.swing.JPanel();
        tfHoraTermino = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfHoraChegadaAgente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfHoraAcionamento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfPlacaAgente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfNomeAgente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbTipoAcionamento = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfTotalKM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfVarredura = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnPrincipal1.setForeground(new java.awt.Color(255, 255, 255));

        pnOcorrencia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da Ocorrencia", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        pnOcorrencia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Cliente");
        pnOcorrencia.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        cbClienteSinistro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Cliente1", "Cliente2", "Cliente3" }));
        pnOcorrencia.add(cbClienteSinistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, -1));

        jLabel5.setText("Tipo de Ocorrencia ");
        pnOcorrencia.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        cbTipoOcorrencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Suspeita de Sinistro", "Sinistro Confirmado", "Preservacao" }));
        pnOcorrencia.add(cbTipoOcorrencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 140, -1));

        pnVeiculo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Veiculo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        pnVeiculo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("Placa :");
        pnVeiculo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 31, -1, -1));
        pnVeiculo.add(tfPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 29, 65, -1));

        jLabel14.setText("Carreta:");
        pnVeiculo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 31, -1, -1));
        pnVeiculo.add(tfCarreta, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 29, 80, -1));

        jLabel16.setText("Modelo");
        pnVeiculo.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 31, -1, -1));
        pnVeiculo.add(tfModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 29, 136, -1));

        jLabel18.setText("Cor:");
        pnVeiculo.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 31, -1, -1));
        pnVeiculo.add(tfCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 29, 75, -1));
        pnVeiculo.add(tfValorCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 75, -1));

        jLabel20.setText("Valor da carga:");
        pnVeiculo.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, -1));
        pnVeiculo.add(tfCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 81, -1));

        jLabel24.setText("Cidade:");
        pnVeiculo.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));
        pnVeiculo.add(tfCoordenadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 130, -1));

        jLabel25.setText("Coordenadas:");
        pnVeiculo.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel1.setText("Isca:");
        pnVeiculo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));
        pnVeiculo.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 100, -1));

        pnOcorrencia.add(pnVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 820, 90));

        jLabel9.setText("Informante:");
        pnOcorrencia.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        tfInformante.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pnOcorrencia.add(tfInformante, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 74, 23));

        jLabel15.setText("Contato");
        pnOcorrencia.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        jLabel17.setText("Hora da ocorrencia");
        pnOcorrencia.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, -1, -1));

        tfHoraOcorrencia.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pnOcorrencia.add(tfHoraOcorrencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 74, 23));
        pnOcorrencia.add(tfContato, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 70, -1));

        btSalvarSinistro.setText("Salvar");
        btSalvarSinistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarSinistroActionPerformed(evt);
            }
        });
        pnOcorrencia.add(btSalvarSinistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, -1, -1));

        btLimparSinistro.setText("Limpar");
        btLimparSinistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparSinistroActionPerformed(evt);
            }
        });
        pnOcorrencia.add(btLimparSinistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 510, -1, -1));

        taDescricao.setColumns(20);
        taDescricao.setRows(5);
        taDescricao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descricao", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jScrollPane3.setViewportView(taDescricao);

        pnOcorrencia.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 590, 150));

        pnCondutor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Condutor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel19.setText("Nome:");

        jLabel21.setText("Cpf:");

        jLabel22.setText("Contato:");

        javax.swing.GroupLayout pnCondutorLayout = new javax.swing.GroupLayout(pnCondutor);
        pnCondutor.setLayout(pnCondutorLayout);
        pnCondutorLayout.setHorizontalGroup(
            pnCondutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCondutorLayout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(19, 19, 19)
                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfContatoCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        pnCondutorLayout.setVerticalGroup(
            pnCondutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCondutorLayout.createSequentialGroup()
                .addGroup(pnCondutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCondutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(tfContatoCondutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnCondutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)
                        .addComponent(tfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnOcorrencia.add(pnCondutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 810, 60));

        pnAcionamento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Acionamento", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        pnAcionamento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnAcionamento.add(tfHoraTermino, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 116, -1));

        jLabel12.setText("Hora do termino");
        pnAcionamento.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        tfHoraChegadaAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHoraChegadaAgenteActionPerformed(evt);
            }
        });
        pnAcionamento.add(tfHoraChegadaAgente, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 80, -1));

        jLabel11.setText("Hora de chegada:");
        pnAcionamento.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));
        pnAcionamento.add(tfHoraAcionamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 80, -1));

        jLabel10.setText("Hora Inicio:");
        pnAcionamento.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));
        pnAcionamento.add(tfPlacaAgente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 90, -1));

        jLabel8.setText("Placa:");
        pnAcionamento.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));
        pnAcionamento.add(tfNomeAgente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 90, -1));

        jLabel7.setText("Agente:");
        pnAcionamento.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        cbTipoAcionamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Antenista", "Pronta-Resposta", "Escolta" }));
        cbTipoAcionamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoAcionamentoItemStateChanged(evt);
            }
        });
        pnAcionamento.add(cbTipoAcionamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, -1));

        jLabel6.setText("Tipo:");
        pnAcionamento.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel2.setText("Total Km:");
        pnAcionamento.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, -1));
        pnAcionamento.add(tfTotalKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 90, -1));

        jLabel3.setText("Varredura:");
        pnAcionamento.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, -1, -1));
        pnAcionamento.add(tfVarredura, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 190, -1));

        pnOcorrencia.add(pnAcionamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 810, 120));

        javax.swing.GroupLayout pnPrincipal1Layout = new javax.swing.GroupLayout(pnPrincipal1);
        pnPrincipal1.setLayout(pnPrincipal1Layout);
        pnPrincipal1Layout.setHorizontalGroup(
            pnPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipal1Layout.createSequentialGroup()
                .addComponent(pnOcorrencia, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnPrincipal1Layout.setVerticalGroup(
            pnPrincipal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPrincipal1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(pnOcorrencia, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnCadastroSinistroLayout = new javax.swing.GroupLayout(pnCadastroSinistro);
        pnCadastroSinistro.setLayout(pnCadastroSinistroLayout);
        pnCadastroSinistroLayout.setHorizontalGroup(
            pnCadastroSinistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnCadastroSinistroLayout.setVerticalGroup(
            pnCadastroSinistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadastroSinistroLayout.createSequentialGroup()
                .addComponent(pnPrincipal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 901, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 20, Short.MAX_VALUE)
                    .addComponent(pnCadastroSinistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 21, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 567, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnCadastroSinistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfHoraChegadaAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHoraChegadaAgenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHoraChegadaAgenteActionPerformed

    private void btSalvarSinistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarSinistroActionPerformed
//        if (cbClienteSinistro.getSelectedIndex() == 0
//            || cbTipoAcionamento.getSelectedIndex() == 0
//            || cbTipoOcorrencia.getSelectedIndex() == 0) {
//            JOptionPane.showMessageDialog(null, "Por favor Preencha todos os campos obrigatorios : Cliente , Tipo da Ocorrencia , Tipo do Acionamento ");
//        } else {
//            Sinistro sinistro = new Sinistro();
//
//            sinistro.setCarreta(tfCarreta.getText());
//            sinistro.setCidade(tfCidade.getText());
//            sinistro.setCliente(cbClienteSinistro.getSelectedItem().toString());
//            sinistro.setContato(tfContato.getText());
//            sinistro.setContatoCondutor(tfContatoCondutor.getText());
//            sinistro.setCoordenadas(tfCoordenadas.getText());
//            sinistro.setCor(tfCor.getText());
//            sinistro.setCpfCondutor(tfCPF.getText());
//            sinistro.setDescricao(taDescricao.getText());
//            sinistro.setEndereco(tfEndereco.getText());
//            sinistro.setHoraAcionamento(tfHoraAcionamento.getText());
//            sinistro.setHoraChegadaAgente(tfHoraChegadaAgente.getText());
//            sinistro.setHoraOcorrencia(tfHoraOcorrencia.getText());
//            sinistro.setHoraTermino(tfHoraTermino.getText());
//            sinistro.setInformante(tfInformante.getText());
//            sinistro.setModelo(tfModelo.getText());
//            sinistro.setNomeAgente(tfNomeAgente.getText());
//            sinistro.setNomeCondutor(tfNome.getText());
//            sinistro.setPlaca(tfPlaca.getText());
//            sinistro.setPlacaAgente(tfPlacaAgente.getText());
//            sinistro.setTipoAcionamento(cbTipoAcionamento.getSelectedItem().toString());
//            sinistro.setTipoOcorrencia(cbTipoOcorrencia.getSelectedItem().toString());
//            sinistro.setValorCarga(Double.valueOf(tfValorCarga.getText().toString()));
//
//            if (sinistro.Gravar(sinistro)) {
//                JOptionPane.showMessageDialog(null, "Dados Salvo com Sucesso");
//            } else {
//                JOptionPane.showMessageDialog(null, "Nao foi possivel salvar os dados");
//            }
//
//        }
    }//GEN-LAST:event_btSalvarSinistroActionPerformed

    private void btLimparSinistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparSinistroActionPerformed
    //    LimparSinistro();
    }//GEN-LAST:event_btLimparSinistroActionPerformed

    private void cbTipoAcionamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoAcionamentoItemStateChanged
             if(cbTipoAcionamento.getSelectedIndex() ==1){
//                 pnAcionamento.removeAll();
//                 pnAcionamento.setLayout(new GridBagLayout());
//                 GridBagConstraints pn = new GridBagConstraints();
//                 JComboBox<String> agentes = new JComboBox<String>();
//                 Agente ag = new Agente();
//                 List<Agente> listaAg = ag.pegarAgentes();
//                 agentes.addItem("Selecione um Agente");
//                 for(int i=0 ; i<listaAg.size(); i ++){
//                     agentes.addItem(listaAg.get(i).getNome());
//                 }
//                 agentes.addItemListener(new ItemListener() {
//                     @Override
//                     public void itemStateChanged(ItemEvent ie) {
//                         if(agentes.getSelectedIndex() == 1){
//                             System.out.println("Rafa");
//                         }
//                     }
//                 });
//                 JLabel lbAgente = new JLabel("Aquiiii:");
//                 JLabel lbteste = new JLabel("Aquiiii222222:");
//                 pn.gridx = 20;
//                 pn.gridy = 2;
//                 pn.fill = GridBagConstraints.WEST;
//                 pnAcionamento.add(agentes,pn);
//                 pn.gridx = 20;
//                 pn.gridy = 0;
//                 pnAcionamento.add(lbAgente,pn);
//                 
//              //   pn.weightx =1;
//                 pn.gridx = 25;
//                 pn.gridy = 5;
//                 pnAcionamento.add(lbteste,pn);
//                 JButton add = new JButton("Adicionar Antenista");
//                 GridBagConstraints pn = new GridBagConstraints();
//           
//                 pn.gridy=100;
//                 pn.gridx=10;
//                 pn.gridheight=100;
//                 pn.fill = GridBagConstraints.LINE_END;
//                pnAcionamento.setLayout(new GridBagLayout());
//                 add.setSize(155, 25);
//                
//                 pnAcionamento.add(add,pn);
              
             }
             repaint();
    }//GEN-LAST:event_cbTipoAcionamentoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSinsitroTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSinsitroTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSinsitroTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSinsitroTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSinsitroTeste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimparSinistro;
    private javax.swing.JButton btSalvarSinistro;
    private javax.swing.JComboBox<String> cbClienteSinistro;
    private javax.swing.JComboBox<String> cbTipoAcionamento;
    private javax.swing.JComboBox<String> cbTipoOcorrencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pnAcionamento;
    private javax.swing.JPanel pnCadastroSinistro;
    private javax.swing.JPanel pnCondutor;
    private javax.swing.JPanel pnOcorrencia;
    public javax.swing.JPanel pnPrincipal1;
    private javax.swing.JPanel pnVeiculo;
    private javax.swing.JTextArea taDescricao;
    private javax.swing.JTextField tfCPF;
    private javax.swing.JTextField tfCarreta;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfContato;
    private javax.swing.JTextField tfContatoCondutor;
    private javax.swing.JTextField tfCoordenadas;
    private javax.swing.JTextField tfCor;
    private javax.swing.JTextField tfHoraAcionamento;
    private javax.swing.JTextField tfHoraChegadaAgente;
    private javax.swing.JTextField tfHoraOcorrencia;
    private javax.swing.JTextField tfHoraTermino;
    private javax.swing.JTextField tfInformante;
    private javax.swing.JTextField tfModelo;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNomeAgente;
    private javax.swing.JTextField tfPlaca;
    private javax.swing.JTextField tfPlacaAgente;
    private javax.swing.JTextField tfTotalKM;
    private javax.swing.JTextField tfValorCarga;
    private javax.swing.JTextField tfVarredura;
    // End of variables declaration//GEN-END:variables
}
