/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Usuario;
import java.awt.event.FocusAdapter;
import javax.swing.JOptionPane;

/**
 *
 * @author rafa_
 */
public class TelaTrocarSenha extends javax.swing.JFrame {

    /**
     * Creates new form TelaUsuario
     */
    public TelaTrocarSenha() {
        initComponents();
       
    }
    public TelaTrocarSenha(String nome){
        initComponents();
        lbMostrarUsuario.setText(nome);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPrincipalMudarSenha = new javax.swing.JPanel();
        pnNovoCadastro = new javax.swing.JPanel();
        tfSenha = new javax.swing.JTextField();
        tfConfirmacao = new javax.swing.JTextField();
        lbConfirmacao = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        btCriar = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();
        lbMostrarUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbConfirmacao.setText("Confirmacao da Senha:");

        lbSenha.setText("Senha:");

        lbUsuario.setText("Usuario:");

        btCriar.setText("Criar");
        btCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCriarActionPerformed(evt);
            }
        });

        lbTitulo.setText("Cadastro de Usuario");

        javax.swing.GroupLayout pnNovoCadastroLayout = new javax.swing.GroupLayout(pnNovoCadastro);
        pnNovoCadastro.setLayout(pnNovoCadastroLayout);
        pnNovoCadastroLayout.setHorizontalGroup(
            pnNovoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNovoCadastroLayout.createSequentialGroup()
                .addGroup(pnNovoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNovoCadastroLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(btCriar))
                    .addGroup(pnNovoCadastroLayout.createSequentialGroup()
                        .addGroup(pnNovoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnNovoCadastroLayout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(lbSenha))
                            .addGroup(pnNovoCadastroLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbConfirmacao)))
                        .addGap(18, 18, 18)
                        .addGroup(pnNovoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfConfirmacao)
                            .addComponent(tfSenha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnNovoCadastroLayout.createSequentialGroup()
                                .addComponent(lbUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbMostrarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNovoCadastroLayout.createSequentialGroup()
                .addGap(0, 195, Short.MAX_VALUE)
                .addComponent(lbTitulo)
                .addGap(168, 168, 168))
        );
        pnNovoCadastroLayout.setVerticalGroup(
            pnNovoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNovoCadastroLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbTitulo)
                .addGap(33, 33, 33)
                .addGroup(pnNovoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbUsuario)
                    .addComponent(lbMostrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnNovoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSenha)
                    .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnNovoCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbConfirmacao)
                    .addComponent(tfConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btCriar)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnPrincipalMudarSenhaLayout = new javax.swing.GroupLayout(pnPrincipalMudarSenha);
        pnPrincipalMudarSenha.setLayout(pnPrincipalMudarSenhaLayout);
        pnPrincipalMudarSenhaLayout.setHorizontalGroup(
            pnPrincipalMudarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalMudarSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnNovoCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnPrincipalMudarSenhaLayout.setVerticalGroup(
            pnPrincipalMudarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalMudarSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnNovoCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(pnPrincipalMudarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(pnPrincipalMudarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriarActionPerformed
      if (tfSenha.getText().equals(tfConfirmacao.getText())){
          Usuario usuario = new Usuario(lbMostrarUsuario.getText(),tfSenha.getText());
          boolean resp = usuario.update();
          if (resp){
              JOptionPane.showMessageDialog(null,"Senha alterada com sucesso !");
          }else {
              System.out.println("verificar erro");
          }
      }else {
          JOptionPane.showMessageDialog(null,"Digite a mesma senha nos dois campos ");
          tfSenha.setText("");
          tfConfirmacao.setText("");
      }
      
    }//GEN-LAST:event_btCriarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTrocarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTrocarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTrocarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTrocarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTrocarSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCriar;
    private javax.swing.JLabel lbConfirmacao;
    private javax.swing.JLabel lbMostrarUsuario;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JPanel pnNovoCadastro;
    private javax.swing.JPanel pnPrincipalMudarSenha;
    private javax.swing.JTextField tfConfirmacao;
    private javax.swing.JTextField tfSenha;
    // End of variables declaration//GEN-END:variables
}
