/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Agente;
import Model.GerarPDF;
import Model.Missao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.commons.math3.util.CentralPivotingStrategy;

/**
 *
 * @author rafa_
 */
public class TelaMissao extends javax.swing.JFrame {

    List<Missao> listaMissao = new ArrayList<Missao>();
    public TelaMissao() {
        initComponents();
        if(listaMissao.size() != 0){
            mostrarEquipes(listaMissao);
            System.out.println("rodouuu principal");
        }
    
        
    }
    public TelaMissao(List<Missao> a) {
        initComponents();
        for (int i =0 ; i<a.size();i++){
            listaMissao.add(a.get(i));
        }
        mostrarEquipes(listaMissao);
    }
    
    public void mostrarEquipes(List<Missao> lista){
        int altura =200;
        JPanel Painel = new JPanel();
        Painel.setSize(500, 32); //32
        Painel.setVisible(true);
        for(int i=0;i<lista.size();i++){
       // listaPainel.get(i).setBorder(javax.swing.BorderFactory.createEtchedBorder());
            if (i==0){
               
          JLabel nome = new JLabel();
          JLabel horarioInicio = new JLabel();
          JLabel horariofim = new JLabel();
          JLabel totalKM = new JLabel();
          JLabel varredura = new JLabel();
          nome.setText("Nome: "+lista.get(i).getAgente().getNome()+"        ");
          horarioInicio.setText("Horario do Inicio: "+lista.get(i).getHorarioInicio()+"        ");
          horariofim.setText("Horario do Fim: "+lista.get(i).getHorarioFim()+"        ");
          totalKM.setText("Total de Km: "+lista.get(i).getTotalKm()+"        ");
          varredura.setText("Locais feito varredura: "+lista.get(i).getVarredura()+"        ");
          nome.setSize(500,100);
          horarioInicio.setSize(500,100);
          horariofim.setSize(500,100);
          totalKM.setSize(500,100);
          varredura.setSize(500,100);
          
          
          
//          nome.setLocation(10, altura);
//          varredura.setLocation(100, altura);
//          totalKM.setLocation(202, altura);
//          horarioInicio.setLocation(352, altura);
//          horariofim.setLocation(402, altura);
          Painel.add(nome);
          Painel.add(horarioInicio);
          Painel.add(horariofim);
          Painel.add(totalKM);
          Painel.add(varredura);
          
          
          pnEquipes.add(Painel);
          altura+=40;
            }else{
               
                JLabel nome = new JLabel();
          JLabel horarioInicio = new JLabel();
          JLabel horariofim = new JLabel();
          JLabel totalKM = new JLabel();
          JLabel varredura = new JLabel();
          nome.setText("Nome: "+lista.get(i).getAgente().getNome()+"        ");
          horarioInicio.setText("Horario do Inicio: "+lista.get(i).getHorarioInicio()+"        ");
          horariofim.setText("Horario do Fim: "+lista.get(i).getHorarioFim()+"        ");
          totalKM.setText("Total de Km: "+lista.get(i).getTotalKm()+"        ");
          varredura.setText("Locais feito varredura: "+lista.get(i).getVarredura()+"        ");
          nome.setSize(500,100);
          horarioInicio.setSize(500,100);
          horariofim.setSize(500,100);
          totalKM.setSize(500,100);
          varredura.setSize(500,100);
   
          
          Painel.add(nome);
          Painel.add(horarioInicio);
          Painel.add(horariofim);
          Painel.add(totalKM);
          Painel.add(varredura);
          
          pnEquipes.add(Painel);
          altura+=40;
            }
          
          
        }
        setSize(getWidth(), getHeight()+1);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btPrincipal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnEquipes = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btPrincipal.setText("Adicionar Agente");
        btPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrincipalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Equipes");

        pnEquipes.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("Gerar PDF");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 462, Short.MAX_VALUE)
                        .addComponent(btPrincipal)
                        .addGap(202, 202, 202)
                        .addComponent(jButton1))
                    .addComponent(pnEquipes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnEquipes, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btPrincipal))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrincipalActionPerformed
//        TelaAgentes telaAgente = new TelaAgentes(listaMissao);
//        listaMissao.add(new Missao(1, 1111111, 12, 200, "Sao Paulo , Registro , Sao joao do miriti"
//                + ""));
//     //   System.out.println(listaMissao.get(0).getImagens().size());
//        
//        mostrarEquipes(listaMissao);
//        setSize(getWidth(), getHeight()+1);
       
    }//GEN-LAST:event_btPrincipalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           if(pnEquipes.getComponentCount() != 0){
               GerarPDF pdf = new GerarPDF();
//               TelaUparImagens tela = new TelaUparImagens(listaMissao, pdf, 0);
   //            tela.setVisible(true);
               setVisible(false);
           }else{
               JOptionPane.showMessageDialog(null, "Primeiro Adicione os Agentes ");
           }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMissao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMissao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPrincipal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnEquipes;
    // End of variables declaration//GEN-END:variables
}
